tasks:
  setupAwsSamCli:
    name: Install AWS SAM CLI
    description: Installs AWS SAM CLI
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/aws_sam_cli_install.sh

  configureAwsCredentials:
    name: Configure AWS Credentials
    description: Sets up AWS credentials
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/aws_credentials.sh
      
  configureGit:
    name: Configure Git User Settings
    description: Set GitHub user email and name
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/git_settings_configure.sh
  
  installPythonPackages:
    name: Install Python Packages
    description: Installs development and AWS-related Python packages
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/python_sdk_install.sh

  installTerraform:
    name: Install Terraform
    description: Installs Terraform CLI
    triggeredBy:
      - postDevcontainerStart
    command: |
      ./bin/terraform_cli_install.sh